### PR TITLE
No longer exiting after TestResults elemen ends

### PR DESCRIPTION
**Pull request by judovana**
thus allwoing to process more <report> in xml file

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by zzambers** [comment]
This seems quite fragile making lot of assumptions. (like calling code using read method with buffer, assumptions about buffer size)

Maybe it would be better to do this in single character read method and then override read with buffer to use it.

**Comment by judovana** [comment]
Oh you mean.. I see now... Worthy to try

**Comment by judovana** [comment]
I'm afraid of quite a performance impact....

**Comment by zzambers** [comment]
> I'm afraid of quite a performance impact....

performance will probably not be the best, but I think it should be much easier to write it correctly (much less corner cases).

**Comment by zzambers** [comment]
Also if performance turns out to be problem, it can be probably mitigated using BufferedReader.

**Comment by judovana** [comment]
HA. Thats probably the best idea ever ;)

**Comment by zzambers** [comment]
:)

I have tested it using:
```
String xml = "<?xml....?><Report>\n</Report>";
InputStream is = new ByteArrayInputStream(xml.getBytes("UTF-8"));
FixingReader fr = new FixingReader(is, "UTF-8");
char[] buf = new char[12];
int read;
StringBuilder sb = new StringBuilder();
while ((read = fr.read(buf, 0, buf.length)) >= 0) {
	sb.append(buf, 0, read);
}
System.out.println(sb.toString());
```

Fixed one issue (check after read in second read method, updated comment).

**Comment by judovana** [comment]
Ok, will try that and meassure performance

**Comment by judovana** [comment]
Waht I miss in that `public int read(char[] cbuf, int off, int len) throws IOException {` is some `if (isFixed) then super.public int read(cbuf,off,len)``

**Comment by zzambers** [comment]
> Waht I miss in that `public int read(char[] cbuf, int off, int len) throws IOException {` is some `if (isFixed) then super.read(cbuf,off,len)`

It is already handled in `read()`, it should just return right thing.

**Comment by zzambers** [comment]
Also code in second method:
```
if (prevChar < 0) {
  return -1;
}
```
may be little paranoia (to handle zero length read after end of the stream has been reached) :)

**Comment by zzambers** [comment]
> > Waht I miss in that `public int read(char[] cbuf, int off, int len) throws IOException {` is some `if (isFixed) then super.read(cbuf,off,len)`
> 
> It is already handled in `read()`, it should just return right thing.

`read(char[] cbuf, int off, int len)` should be just simple generic implementation using `read()` method, where no additional processing is done

**Comment by zzambers** [comment]
> @zzambers ITt seems yours solution fails with proepr
> 
> ```
> <?xml?>
> <report>
> ```
> 
> one....
> 
> The perf test is currenlty dying with semie xpected `java.lang.OutOfMemoryError: Java heap space` willcontinue to work on that

Strange, with proper report data it should just add additional newline.

**Comment by zzambers** [comment]
I have tried to update test to have newline after `<?xml....?>` and it just adds additional newline (blank line after first line).

**Comment by judovana** [comment]
> > Waht I miss in that `public int read(char[] cbuf, int off, int len) throws IOException {` is some `if (isFixed) then super.read(cbuf,off,len)`
> 
> It is already handled in `read()`, it should just return right thing.

I had noticed that. But original  `public int read(char[] cbuf, int off, int len) `  do not call `read()`  at all.

**Comment by judovana** [comment]
> I have tried to update test to have newline after `<?xml....?>` and it just adds additional newline (blank line after first line).

Thats what I was expecting too. Will try to sum up the benchmarks today.

**Comment by judovana** [comment]
> > > Waht I miss in that `public int read(char[] cbuf, int off, int len) throws IOException {` is some `if (isFixed) then super.read(cbuf,off,len)`
> > 
> > 
> > It is already handled in `read()`, it should just return right thing.
> 
> `read(char[] cbuf, int off, int len)` should be just simple generic implementation using `read()` method, where no additional processing is done

In theory yes, but in practis  `public int read(char[] cbuf, int off, int len)` do a lot of optimisations anmd is not using `read` at all.

**Comment by zzambers** [comment]
> > > > Waht I miss in that `public int read(char[] cbuf, int off, int len) throws IOException {` is some `if (isFixed) then super.read(cbuf,off,len)`
> > > 
> > > 
> > > It is already handled in `read()`, it should just return right thing.
> > 
> > 
> > `read(char[] cbuf, int off, int len)` should be just simple generic implementation using `read()` method, where no additional processing is done
> 
> In theory yes, but in practis `public int read(char[] cbuf, int off, int len)` do a lot of optimisations anmd is not using `read` at all.

Yy, I meant my implementation. I think we should first make sure it's correct and only then make optimizations of it if necessary...

**Comment by judovana** [comment]
It is necessary... I have some weird xmls which do niot cooperate (which is strange, as those are xmls from our infra), and the performance impact seems gigantic (I have never seen it finished)

**Comment by zzambers** [comment]
I hoped this will be ok for initial tests. :(

What about wrapping inputstreams to BufferedInputStreams? (May be slow if it calls some underlying system calls one byte at a time).

**Comment by zzambers** [comment]
Also second read could be made little bit less lazy and actually fill more than one char :)
```
	public int read(char[] cbuf, int off, int len) throws IOException {
		if (prevChar < 0) {
			return -1;
		}
		if (len == 0) {
			return 0;
		}
		for (int i = 0; i < len; ++i) {
			int c = read();
			if (c < 0) { // EOF
				return i == 0 ? -1 : i;
			}
			cbuf[off + i] = (char) c;
		
		}
		return len;
	}
```

**Comment by judovana** [comment]
@zzambers  If anythig wrong, please fix, por revert this one.  /me of and away

**Pull request merged**
